//! Independent checksum golden-vector evidence.
//!
//! The expected values in `tests/fixtures/checksum/xxh3_128_reference.json`
//! were generated by the **official xxHash C reference implementation**
//! (Cyan4973/xxHash `v0.8.2`, tag commit
//! `bbb27a5efb85b92a0486cf361a8635715a53f6ba`) via
//! `scripts/checksum-generate-goldens.sh`. They are deliberately *not*
//! produced by `twox-hash`, so these tests compare the Rust production path
//! against an independent implementation rather than against itself.
//!
//! The C generator additionally asserts, for every vector, that
//! `XXH3_128bits` (oneshot) equals the streaming API over many chunkings; the
//! Rust side then re-checks its own `Digest` streaming path against the same
//! fixed expectations. Provenance and hashes are recorded in
//! `scripts/checksum-provenance.txt` and echoed inside the fixture.
//!
//! Serialization under test is SREP-NG v3: low64 little-endian
//! followed by high64 little-endian, NOT the big-endian `XXH128_canonical`
//! representation.

use serde_json::Value;
use srep::checksum::{Digest, encode_xxh3, oneshot};
use srep::config::Checksum;

const FIXTURE: &str = include_str!("fixtures/checksum/xxh3_128_reference.json");

#[derive(Debug, Clone)]
struct Vector {
    profile: String,
    len: usize,
    input_fnv1a64: u64,
    low64: u64,
    high64: u64,
    serialized: Vec<u8>,
}

fn parse_hex_u64(s: &str) -> u64 {
    assert_eq!(s.len(), 16, "expected 16 hex digits, got {s:?}");
    u64::from_str_radix(s, 16).expect("hex u64")
}

fn parse_hex_bytes(s: &str) -> Vec<u8> {
    assert!(s.len().is_multiple_of(2), "odd hex length");
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).expect("hex byte"))
        .collect()
}

/// Mirror of the deterministic input generator in
/// `scripts/checksum-generate-c-goldens.c`. Any divergence is caught by the
/// `input_fnv1a64` anchor check before the digest comparison.
fn build_input(profile: &str, len: usize) -> Vec<u8> {
    (0..len)
        .map(|i| match profile {
            "xor" => (i as u32 * 131 + 17) as u8 ^ ((i >> 3) as u8),
            "zeros" => 0x00,
            "repeated" => 0xAB,
            "descend" => (255u32 - (i as u32 & 0xff)) as u8,
            other => panic!("unknown profile {other:?}"),
        })
        .collect()
}

fn fnv1a64(bytes: &[u8]) -> u64 {
    let mut hash: u64 = 0xcbf29ce484222325;
    for &byte in bytes {
        hash ^= u64::from(byte);
        hash = hash.wrapping_mul(0x100000001b3);
    }
    hash
}

fn load_vectors() -> Vec<Vector> {
    let root: Value = serde_json::from_str(FIXTURE).expect("fixture is valid JSON");

    assert_eq!(root["schema"], "srep-checksum-xxh3-v1");
    assert_eq!(root["algorithm"], "XXH3-128");
    assert_eq!(root["seed"], 0);
    assert_eq!(root["secret"], "official-default");
    assert_eq!(root["serialization"], "low64-le-then-high64-le");

    let reference = &root["reference"];
    assert_eq!(reference["project"], "Cyan4973/xxHash");
    assert_eq!(reference["tag"], "v0.8.2");
    assert_eq!(
        reference["tag_commit"],
        "bbb27a5efb85b92a0486cf361a8635715a53f6ba"
    );

    root["vectors"]
        .as_array()
        .expect("vectors array")
        .iter()
        .map(|v| Vector {
            profile: v["profile"].as_str().expect("profile").to_owned(),
            len: v["len"].as_u64().expect("len") as usize,
            input_fnv1a64: parse_hex_u64(v["input_fnv1a64"].as_str().expect("fnv")),
            low64: parse_hex_u64(v["low64"].as_str().expect("low64")),
            high64: parse_hex_u64(v["high64"].as_str().expect("high64")),
            serialized: parse_hex_bytes(v["serialized_hex"].as_str().expect("serialized_hex")),
        })
        .collect()
}

#[test]
fn fixture_has_broad_boundary_and_profile_coverage() {
    let vectors = load_vectors();
    assert!(
        vectors.len() >= 48,
        "expected a broad vector set, got {}",
        vectors.len()
    );

    let lengths: std::collections::BTreeSet<usize> = vectors.iter().map(|v| v.len).collect();
    // Canonical XXH3 cutovers plus large multi-block / streaming cases.
    for required in [
        0usize, 1, 2, 3, 4, 8, 15, 16, 17, 31, 32, 33, 63, 64, 65, 127, 128, 129, 239, 240, 241,
        255, 256, 257, 511, 512, 1023, 1024, 4096, 65537,
    ] {
        assert!(
            lengths.contains(&required),
            "boundary length {required} missing from fixture"
        );
    }
    assert!(
        lengths.contains(&262_144),
        "large multi-block streaming length missing"
    );

    let profiles: std::collections::BTreeSet<&str> =
        vectors.iter().map(|v| v.profile.as_str()).collect();
    for required in ["xor", "zeros", "repeated", "descend"] {
        assert!(profiles.contains(required), "profile {required} missing");
    }
}

#[test]
fn xxh3_oneshot_matches_independent_c_goldens() {
    for vector in load_vectors() {
        let input = build_input(&vector.profile, vector.len);
        assert_eq!(
            fnv1a64(&input),
            vector.input_fnv1a64,
            "input generator drift for profile {} len {}",
            vector.profile,
            vector.len
        );

        let actual = oneshot(Checksum::Xxh3, &input);
        assert_eq!(
            actual, vector.serialized,
            "oneshot mismatch for {} len {}",
            vector.profile, vector.len
        );

        // Explicit low/high order, not just opaque bytes.
        let mut expected_serialized = Vec::with_capacity(16);
        expected_serialized.extend_from_slice(&vector.low64.to_le_bytes());
        expected_serialized.extend_from_slice(&vector.high64.to_le_bytes());
        assert_eq!(actual, expected_serialized, "low/high LE order");
        assert_ne!(
            actual,
            {
                let mut big = Vec::new();
                big.extend_from_slice(&vector.high64.to_be_bytes());
                big.extend_from_slice(&vector.low64.to_be_bytes());
                big
            },
            "must not be canonical big-endian XXH128 order"
        );
    }
}

#[test]
fn xxh3_streaming_digest_matches_independent_c_goldens_across_chunkings() {
    // Chunk sizes intentionally include the ones the C generator exercises,
    // plus Rust-specific splits around the 240/241 stripe cutoff.
    let chunk_sizes = [
        1usize, 2, 3, 7, 8, 15, 16, 31, 63, 64, 127, 128, 240, 241, 255, 256, 257, 512, 1024, 4096,
        65536,
    ];

    for vector in load_vectors() {
        let input = build_input(&vector.profile, vector.len);

        // Whole-buffer streaming.
        let mut whole = Digest::new(Checksum::Xxh3);
        whole.update(&input);
        assert_eq!(
            whole.finalize(),
            vector.serialized,
            "whole-buffer streaming mismatch for {} len {}",
            vector.profile,
            vector.len
        );

        for chunk in chunk_sizes {
            let mut digest = Digest::new(Checksum::Xxh3);
            for piece in input.chunks(chunk) {
                digest.update(piece);
            }
            assert_eq!(
                digest.finalize(),
                vector.serialized,
                "streaming mismatch for {} len {} at chunk {}",
                vector.profile,
                vector.len,
                chunk
            );
        }
    }
}

#[test]
fn encode_xxh3_matches_fixture_word_order() {
    for vector in load_vectors() {
        let combined = (u128::from(vector.high64) << 64) | u128::from(vector.low64);
        let encoded = encode_xxh3(combined);
        assert_eq!(
            encoded, vector.serialized,
            "encode_xxh3 word order for {} len {}",
            vector.profile, vector.len
        );
        assert_eq!(&encoded[..8], &vector.low64.to_le_bytes());
        assert_eq!(&encoded[8..], &vector.high64.to_le_bytes());
    }
}

#[test]
fn xxh3_explicit_known_empty_vector_low_high_order() {
    // The canonical XXH3-128 of the empty string. This is a named,
    // independently known value (also present in the C golden fixture) that
    // pins the low/high split, not merely the 16 opaque bytes.
    let input: &[u8] = b"";
    let expected_low: u64 = 0x6001_c324_468d_497f;
    let expected_high: u64 = 0x99aa_06d3_0147_98d8;

    let actual = oneshot(Checksum::Xxh3, input);
    let mut expected = Vec::new();
    expected.extend_from_slice(&expected_low.to_le_bytes());
    expected.extend_from_slice(&expected_high.to_le_bytes());
    assert_eq!(actual, expected);
    assert_eq!(actual.len(), 16);

    let mut streaming = Digest::new(Checksum::Xxh3);
    streaming.update(input);
    assert_eq!(streaming.finalize(), expected);
}

#[test]
fn blake3_official_vectors_and_v3_serialization() {
    // Official BLAKE3 test-vector digests for the standard `(0..=250)`-cycle
    // input, and confirmation that the v2 archive serialization is the raw
    // 32-byte digest in digest order (no reordering).
    let input = |len: usize| -> Vec<u8> { (0u8..=250).cycle().take(len).collect() };

    let cases = [
        (
            0usize,
            "af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262",
        ),
        (
            1,
            "2d3adedff11b61f14c886e35afa036736dcd87a74d27b5c1510225d0f592e213",
        ),
        (
            1024,
            "42214739f095a406f3fc83deb889744ac00df831c10daa55189b5d121c855af7",
        ),
    ];

    for (len, expected_hex) in cases {
        let bytes = input(len);
        let expected: Vec<u8> = parse_hex_bytes(expected_hex);
        assert_eq!(expected.len(), 32, "BLAKE3-256 width");

        let actual = oneshot(Checksum::Blake3, &bytes);
        assert_eq!(hex(&actual), expected_hex, "oneshot len {len}");

        let mut streaming = Digest::new(Checksum::Blake3);
        streaming.update(&bytes);
        assert_eq!(streaming.finalize(), expected, "streaming len {len}");

        // BLAKE3 v3 serialization is the raw digest, so `oneshot` equals the
        // fixture bytes directly with no low/high split.
        assert_eq!(actual, expected, "raw digest order len {len}");
    }
}

fn hex(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}
