#!/usr/bin/env python3
"""Portable, non-mutating-by-default generator/checker for SREP-NG XXH3
independent XXH3-128 golden fixture.

Design spec: docs/superpowers/specs/2026-08-30-srep-capability-fidelity-design.md
section 10.10 ("The project MUST maintain its own golden vectors generated from
official C").

Modes
-----
--check (DEFAULT)
    Download/verify the pinned official xxHash C reference, build the small
    generator, emit into a private temporary file, and byte-compare it against
    the committed fixture. Exits nonzero on any difference. Never modifies the
    committed fixture, so a CI "regenerate + test" step cannot silently bless a
    changed C output.

--write / --regenerate
    Same pipeline, but atomically publishes the generated bytes to
    --fixture/--out. This is the only mode that writes tracked output.

Portability
-----------
Only the Python standard library is used (hashlib, urllib, tarfile,
subprocess, tempfile, shutil, argparse, shlex). The C compiler is selected
explicitly via --cc or the SREP_CHECKSUM_CC / CC environment variable, falling
back to a small search of cl / clang / gcc / cc. MSVC (`cl`) and clang/gcc
argument styles are both handled. Extra compiler flags come from --cflags
(repeatable, shell-quoted) or the CFLAGS environment variable; word-size or
target flags are passed cleanly as separate argv tokens, never by embedding a
space inside CC.

The work directory is chosen from SREP_CHECKSUM_CACHE, else RUNNER_TEMP (set by
GitHub Actions, present on Windows), else a unique directory under
/tmp/opencode. Nothing is written into the repository except in --write mode,
and even then via a same-directory temporary file that is atomically replaced.

Safety
------
Downloads are bounded and hashed before extraction; the tarball is extracted
with explicit path-traversal rejection; the total download size is capped.
All failures produce deterministic, path-light error messages.

Provenance pins are duplicated in scripts/checksum-provenance.txt and checked
by the test suite.
"""

from __future__ import annotations

import argparse
import hashlib
import os
import pathlib
import shlex
import shutil
import subprocess
import sys
import tarfile
import tempfile
import urllib.request

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
DEFAULT_FIXTURE = REPO_ROOT / "tests" / "fixtures" / "checksum" / "xxh3_128_reference.json"
GEN_SRC = REPO_ROOT / "scripts" / "checksum-generate-c-goldens.c"

URL = "https://github.com/Cyan4973/xxHash/archive/refs/tags/v0.8.2.tar.gz"
TARBALL_SHA256 = "baee0c6afd4f03165de7a4e67988d16f0f2b257b51d0e3cb91909302a26a79c4"
XXHASH_H_SHA256 = "be275e9db21a503c37f24683cdb4908f2370a3e35ab96e02c4ea73dc8e399c43"
XXHASH_C_SHA256 = "685ac6e9e32d1b5800ccb67cf3698c7f3f30130c159d385b5de34bf4d07a8e70"
EXTRACT_DIRNAME = "xxHash-0.8.2"
MAX_DOWNLOAD_BYTES = 8 * 1024 * 1024  # generous ceiling well above the ~1.1 MiB tarball


class GoldenError(Exception):
    """Deterministic, user-facing failure."""


def sha256_file(path: pathlib.Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def verify_sha256(path: pathlib.Path, expected: str, what: str) -> None:
    actual = sha256_file(path)
    if actual != expected:
        raise GoldenError(f"checksum mismatch for {what}: expected {expected}, got {actual}")


def pick_work_dir(override: str | None) -> pathlib.Path:
    if override:
        path = pathlib.Path(override)
        path.mkdir(parents=True, exist_ok=True)
        return path
    env_cache = os.environ.get("SREP_CHECKSUM_CACHE")
    if env_cache:
        path = pathlib.Path(env_cache)
        path.mkdir(parents=True, exist_ok=True)
        return path
    runner_temp = os.environ.get("RUNNER_TEMP")
    if runner_temp:
        base = pathlib.Path(runner_temp)
        if base.is_dir():
            return pathlib.Path(tempfile.mkdtemp(prefix="srep-c-checksum-", dir=base))
    try:
        return pathlib.Path(tempfile.mkdtemp(prefix="srep-c-checksum-", dir="/tmp/opencode"))
    except OSError:
        return pathlib.Path(tempfile.mkdtemp(prefix="srep-c-checksum-"))


def fetch_tarball(work: pathlib.Path, allow_network: bool) -> pathlib.Path:
    tarball = work / "xxhash-v0.8.2.tar.gz"
    if tarball.is_file() and sha256_file(tarball) == TARBALL_SHA256:
        return tarball
    if not allow_network:
        raise GoldenError(
            "pinned xxHash tarball missing from the work directory and "
            "--no-network was given"
        )
    request = urllib.request.Request(URL, headers={"User-Agent": "srep-checksum-goldens"})
    digest = hashlib.sha256()
    total = 0
    with urllib.request.urlopen(request, timeout=60) as response, tarball.open("wb") as handle:
        while True:
            block = response.read(65536)
            if not block:
                break
            total += len(block)
            if total > MAX_DOWNLOAD_BYTES:
                handle.close()
                tarball.unlink(missing_ok=True)
                raise GoldenError(f"download exceeded {MAX_DOWNLOAD_BYTES} bytes")
            digest.update(block)
            handle.write(block)
    if digest.hexdigest() != TARBALL_SHA256:
        actual = digest.hexdigest()
        tarball.unlink(missing_ok=True)
        raise GoldenError(
            f"checksum mismatch for downloaded tarball: expected {TARBALL_SHA256}, got {actual}"
        )
    return tarball


def safe_extract(tarball: pathlib.Path, destination: pathlib.Path) -> None:
    destination = destination.resolve()
    with tarfile.open(tarball, "r:gz") as archive:
        members = archive.getmembers()
        for member in members:
            member_path = (destination / member.name).resolve()
            if member_path != destination and destination not in member_path.parents:
                raise GoldenError(f"refusing unsafe path in archive: {member.name}")
            if member.issym() or member.islnk():
                link_target = (member_path.parent / member.linkname).resolve()
                if link_target != destination and destination not in link_target.parents:
                    raise GoldenError(f"refusing unsafe link in archive: {member.name}")
        archive.extractall(destination)


def prepare_reference(work: pathlib.Path, allow_network: bool) -> pathlib.Path:
    tarball = fetch_tarball(work, allow_network)
    verify_sha256(tarball, TARBALL_SHA256, "xxHash tarball")

    extract = work / EXTRACT_DIRNAME
    header = extract / "xxhash.h"
    source = extract / "xxhash.c"
    if not (header.is_file() and source.is_file()):
        safe_extract(tarball, work)
    verify_sha256(header, XXHASH_H_SHA256, "xxhash.h")
    verify_sha256(source, XXHASH_C_SHA256, "xxhash.c")
    return extract


def split_flags(values: list[str] | None) -> list[str]:
    flags: list[str] = []
    for value in values or []:
        flags.extend(shlex.split(value))
    env_flags = os.environ.get("CFLAGS")
    if env_flags:
        flags.extend(shlex.split(env_flags))
    return flags


def compiler_is_msvc(compiler: str) -> bool:
    stem = pathlib.Path(compiler).name.lower()
    return stem in {"cl", "cl.exe", "clang-cl", "clang-cl.exe"}


def compile_generator(
    extract: pathlib.Path,
    work: pathlib.Path,
    compiler: str,
    flags: list[str],
) -> pathlib.Path:
    exe_suffix = ".exe" if os.name == "nt" else ""
    generator = work / f"checksum-generate-c-goldens{exe_suffix}"
    source = GEN_SRC
    reference = extract / "xxhash.c"
    if compiler_is_msvc(compiler):
        command = [
            compiler,
            "/nologo",
            "/std:c11",
            "/O2",
            "/W4",
            f"/I{extract}",
            *flags,
            f"/Fe:{generator}",
            str(source),
            str(reference),
        ]
    else:
        command = [
            compiler,
            "-O2",
            "-std=c11",
            "-Wall",
            "-Wextra",
            *flags,
            "-I",
            str(extract),
            "-o",
            str(generator),
            str(source),
            str(reference),
        ]
    try:
        completed = subprocess.run(command, capture_output=True, text=True)
    except OSError as error:
        raise GoldenError(f"could not run C compiler {compiler}: {error}") from error
    if completed.returncode != 0:
        detail = (completed.stderr or completed.stdout).strip().splitlines()
        informative = next(
            (line.strip() for line in detail if "error" in line.lower()),
            detail[-1].strip() if detail else f"exit {completed.returncode}",
        )
        raise GoldenError(f"C compiler failed ({compiler}): {informative}")
    if not generator.is_file():
        raise GoldenError(f"C compiler did not produce {generator.name}")
    return generator


def select_compiler(explicit: str | None) -> str:
    candidate = explicit or os.environ.get("SREP_CHECKSUM_CC") or os.environ.get("CC")
    if candidate:
        return candidate
    for name in ("cl", "clang", "gcc", "cc"):
        found = shutil.which(name)
        if found:
            return found
    raise GoldenError(
        "no C compiler found; pass --cc or set SREP_CHECKSUM_CC/CC "
        "(Windows: cl after VS env init; macOS: clang; Linux: cc)"
    )


def generate_bytes(
    work: pathlib.Path,
    compiler: str | None,
    cflags: list[str] | None,
    allow_network: bool,
) -> bytes:
    extract = prepare_reference(work, allow_network)
    resolved_compiler = select_compiler(compiler)
    generator = compile_generator(extract, work, resolved_compiler, split_flags(cflags))
    try:
        completed = subprocess.run([str(generator)], capture_output=True)
    except OSError as error:
        raise GoldenError(f"could not run generator: {error}") from error
    if completed.returncode != 0:
        raise GoldenError(
            f"generator failed with exit {completed.returncode}"
            " (internal streaming/oneshot mismatch or write error)"
        )
    output = completed.stdout
    if not output.endswith(b"\n"):
        output += b"\n"
    if b'"profile"' not in output:
        raise GoldenError("generator produced no vectors")
    return output


def atomic_write(path: pathlib.Path, data: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    # Match the existing file's mode when replacing; otherwise create a normal
    # world-readable file (tempfile.mkstemp defaults to 0600, which is wrong
    # for a committed fixture).
    if path.exists():
        mode = path.stat().st_mode & 0o7777
    else:
        umask = os.umask(0)
        os.umask(umask)
        mode = 0o666 & ~umask
    fd, tmp_name = tempfile.mkstemp(prefix=path.name + ".", suffix=".tmp", dir=str(path.parent))
    tmp = pathlib.Path(tmp_name)
    try:
        with os.fdopen(fd, "wb") as handle:
            handle.write(data)
        os.chmod(tmp, mode)
        os.replace(tmp, path)
    finally:
        tmp.unlink(missing_ok=True)


def describe_diff(expected: bytes, actual: bytes) -> str:
    if expected == actual:
        return "identical"
    expected_lines = expected.splitlines()
    actual_lines = actual.splitlines()
    if len(expected_lines) != len(actual_lines):
        return f"line count differs: expected {len(expected_lines)}, got {len(actual_lines)}"
    for index, (left, right) in enumerate(zip(expected_lines, actual_lines), start=1):
        if left != right:
            return f"first differing line {index}"
    return "bytes differ only in trailing/newline content"


def run(args: argparse.Namespace) -> int:
    fixture = pathlib.Path(args.fixture).resolve()
    work_override = args.work_dir
    work = pick_work_dir(work_override)
    owned_work = work_override is None and not os.environ.get("SREP_CHECKSUM_CACHE")
    try:
        output = generate_bytes(work, args.cc, args.cflags, not args.no_network)
        vector_marker = b'"profile"'
        vector_count = output.count(vector_marker)
        if args.mode == "write":
            atomic_write(fixture, output)
            print(f"wrote {fixture} ({vector_count} vectors)")
            return 0
        # Default: non-mutating check.
        if not fixture.is_file():
            print(f"CHECK FAILED: fixture missing: {fixture}", file=sys.stderr)
            return 2
        expected = fixture.read_bytes()
        if expected != output:
            print(
                f"CHECK FAILED: generated reference differs from {fixture} "
                f"({describe_diff(expected, output)})",
                file=sys.stderr,
            )
            return 2
        print(f"CHECK OK: {fixture} matches official C ({vector_count} vectors)")
        return 0
    finally:
        if owned_work:
            shutil.rmtree(work, ignore_errors=True)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Generate or check the independent XXH3-128 golden fixture."
    )
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument(
        "--check",
        dest="mode",
        action="store_const",
        const="check",
        help="verify the committed fixture against official C (default, non-mutating)",
    )
    mode.add_argument(
        "--write",
        "--regenerate",
        dest="mode",
        action="store_const",
        const="write",
        help="publish the generated bytes to the fixture path",
    )
    parser.set_defaults(mode="check")
    parser.add_argument(
        "--fixture",
        "--out",
        default=str(DEFAULT_FIXTURE),
        help="fixture path to check or write (default: committed fixture)",
    )
    parser.add_argument(
        "--work-dir",
        default=None,
        help="work directory (default: SREP_CHECKSUM_CACHE, else RUNNER_TEMP, else /tmp/opencode)",
    )
    parser.add_argument(
        "--cc",
        default=None,
        help="C compiler executable (default: SREP_CHECKSUM_CC/CC, else cl/clang/gcc/cc)",
    )
    parser.add_argument(
        "--cflags",
        action="append",
        default=[],
        metavar="FLAGS",
        help="extra compiler flags, shell-quoted; repeatable (also reads CFLAGS)",
    )
    parser.add_argument(
        "--no-network",
        action="store_true",
        help="fail instead of downloading; requires a cached pinned tarball",
    )
    return parser


def normalize_argv(argv: list[str]) -> list[str]:
    """Allow option values that begin with '-' (e.g. `--cflags -m32`).

    argparse otherwise treats a leading '-' as another option. We rewrite
    `--opt value` into `--opt=value` for the value-taking options, without
    touching `--opt=value` forms or values that are plainly separate tokens.
    """
    value_options = {"--fixture", "--out", "--work-dir", "--cc", "--cflags"}
    known_switches = {"--check", "--write", "--regenerate", "--no-network", "-h", "--help"}
    normalized: list[str] = []
    index = 0
    while index < len(argv):
        token = argv[index]
        if token in value_options and index + 1 < len(argv):
            value = argv[index + 1]
            if value not in known_switches:
                normalized.append(f"{token}={value}")
                index += 2
                continue
        normalized.append(token)
        index += 1
    return normalized


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(normalize_argv(list(sys.argv[1:] if argv is None else argv)))
    try:
        return run(args)
    except GoldenError as error:
        print(f"ERROR: {error}", file=sys.stderr)
        return 2
    except KeyboardInterrupt:
        return 130


if __name__ == "__main__":
    raise SystemExit(main())
